import { ICard } from 'src/cards/types/cards.types';
import {
  unstableOre,
  seismicShock,
  asteroidCollapse,
  quantumCoin,
  terraCore,
  mineralGarden,
  orbitalInnovation,
  basicShield,
  overtimeShield,
  planetaryWall,
  foundationArray,
  orbitalMines,
  asteroidVein,
  mineCollapse,
  techHijack,
  reinforcedPlating,
  subterraneanStreams,
  orbitalDrill,
  cosmicExcavator,
  laborArray,
  shockwave,
  grandShield,
  hiddenCavity,
  orbitalVault,
  plasmaSpire,
  orbitalBarricade,
  stellarCore,
  orbitalBastion,
  fortifyArray,
  newFrontiers,
  ultimateShield,
  fieldSwap,
  orbitalCannon,
  coreReactor,
} from './nanomaterials.effects';

export const nanomaterialsCards: ICard[] = [
  {
    id: 'nm_001',
    name: 'Unstable Ore',
    type: 'nanomaterials',
    cost: 0,
    description: 'All players lose 8 nanomaterials.',
    effect: unstableOre,
  },
  {
    id: 'nm_002',
    name: 'Seismic Shock',
    type: 'nanomaterials',
    cost: 0,
    description: '-1 nanomaterial/turn all players.',
    effect: seismicShock,
  },
  {
    id: 'nm_003',
    name: 'Asteroid Collapse',
    type: 'nanomaterials',
    cost: 0,
    description: '-1 nanomaterial/turn, +10 integrity, +5 psi.',
    effect: asteroidCollapse,
  },
  {
    id: 'nm_004',
    name: 'Lucky Pulsar',
    type: 'nanomaterials',
    cost: 0,
    description: '+2 nanomaterials, +2 psi energy, play again.',
    effect: quantumCoin,
  },
  {
    id: 'nm_005',
    name: 'Terra Core',
    type: 'nanomaterials',
    cost: 1,
    description: '+1 integrity. Play again.',
    effect: terraCore,
  },
  {
    id: 'nm_006',
    name: 'Mineral Garden',
    type: 'nanomaterials',
    cost: 1,
    description: '+1 integrity, +1 shield, +2 drones.',
    effect: mineralGarden,
  },
  {
    id: 'nm_007',
    name: 'Orbital Innovation',
    type: 'nanomaterials',
    cost: 2,
    description: '+1 nanomaterial/turn all, +4 psi energy.',
    effect: orbitalInnovation,
  },
  {
    id: 'nm_008',
    name: 'Basic Shield',
    type: 'nanomaterials',
    cost: 2,
    description: '+3 planet integrity.',
    effect: basicShield,
  },
  {
    id: 'nm_009',
    name: 'Overtime Shield',
    type: 'nanomaterials',
    cost: 2,
    description: '+5 integrity, lose 6 psi energy.',
    effect: overtimeShield,
  },
  {
    id: 'nm_010',
    name: 'Planetary Wall',
    type: 'nanomaterials',
    cost: 3,
    description: '+4 planet integrity.',
    effect: planetaryWall,
  },
  {
    id: 'nm_011',
    name: 'Foundation Array',
    type: 'nanomaterials',
    cost: 3,
    description: '+5 integrity if integrity = 0, else +3',
    effect: foundationArray,
  },
  {
    id: 'nm_012',
    name: 'Orbital Mines',
    type: 'nanomaterials',
    cost: 3,
    description: '+1 nanomaterial/turn.',
    effect: orbitalMines,
  },
  {
    id: 'nm_013',
    name: 'Asteroid Vein',
    type: 'nanomaterials',
    cost: 4,
    description: '+2 nanomaterial if < enemy; else +1.',
    effect: asteroidVein,
  },
  {
    id: 'nm_014',
    name: 'Mine Collapse',
    type: 'nanomaterials',
    cost: 4,
    description: '-1 enemy nanomaterial/turn.',
    effect: mineCollapse,
  },
  {
    id: 'nm_015',
    name: 'Tech Hijack',
    type: 'nanomaterials',
    cost: 5,
    description: 'Set your nanomaterial/turn = enemy if lower.',
    effect: techHijack,
  },
  {
    id: 'nm_016',
    name: 'Reinforced Plating',
    type: 'nanomaterials',
    cost: 5,
    description: '+6 shield.',
    effect: reinforcedPlating,
  },
  {
    id: 'nm_017',
    name: 'Subterranean Streams',
    type: 'nanomaterials',
    cost: 6,
    description: 'Lower shield: -1 drone/turn, -2 integrity.',
    effect: subterraneanStreams,
  },
  {
    id: 'nm_018',
    name: 'Orbital Drill',
    type: 'nanomaterials',
    cost: 6,
    description: '+2 nanomaterial/turn.',
    effect: orbitalDrill,
  },
  {
    id: 'nm_019',
    name: 'Cosmic Excavator',
    type: 'nanomaterials',
    cost: 7,
    description: '+4 integrity, +1 nanomaterial/turn.',
    effect: cosmicExcavator,
  },
  {
    id: 'nm_020',
    name: 'Labor Array',
    type: 'nanomaterials',
    cost: 7,
    description: '+9 integrity, lose 5 drones.',
    effect: laborArray,
  },
  {
    id: 'nm_021',
    name: 'Shockwave',
    type: 'nanomaterials',
    cost: 7,
    description: 'All lose 5 integrity. Play again.',
    effect: shockwave,
  },
  {
    id: 'nm_022',
    name: 'Grand Shield',
    type: 'nanomaterials',
    cost: 8,
    description: '+8 shield.',
    effect: grandShield,
  },
  {
    id: 'nm_023',
    name: 'Hidden Cavity',
    type: 'nanomaterials',
    cost: 8,
    description: '+1 psi/turn. Play again.',
    effect: hiddenCavity,
  },
  {
    id: 'nm_024',
    name: 'Orbital Vault',
    type: 'nanomaterials',
    cost: 9,
    description: '+5 shield, +1 drone/turn.',
    effect: orbitalVault,
  },
  {
    id: 'nm_025',
    name: 'Plasma Spire',
    type: 'nanomaterials',
    cost: 9,
    description: '+7 integrity, +7 psi energy.',
    effect: plasmaSpire,
  },
  {
    id: 'nm_026',
    name: 'Orbital Barricade',
    type: 'nanomaterials',
    cost: 10,
    description: '+6 drones, +6 integrity, +1 drone/turn if < enemy.',
    effect: orbitalBarricade,
  },
  {
    id: 'nm_027',
    name: 'Stellar Core',
    type: 'nanomaterials',
    cost: 11,
    description: '+3 integrity, +6 shield.',
    effect: stellarCore,
  },
  {
    id: 'nm_028',
    name: 'Orbital Bastion',
    type: 'nanomaterials',
    cost: 13,
    description: '+12 shield.',
    effect: orbitalBastion,
  },
  {
    id: 'nm_029',
    name: 'Fortify Array',
    type: 'nanomaterials',
    cost: 14,
    description: '+7 shield, 6 damage enemy.',
    effect: fortifyArray,
  },
  {
    id: 'nm_030',
    name: 'New Frontiers',
    type: 'nanomaterials',
    cost: 15,
    description: '+8 shield, +5 integrity.',
    effect: newFrontiers,
  },
  {
    id: 'nm_031',
    name: 'Ultimate Shield',
    type: 'nanomaterials',
    cost: 16,
    description: '+15 shield.',
    effect: ultimateShield,
  },
  {
    id: 'nm_032',
    name: 'Field Swap',
    type: 'nanomaterials',
    cost: 17,
    description: 'Swap your shield with enemy.',
    effect: fieldSwap,
  },
  {
    id: 'nm_033',
    name: 'Orbital Cannon',
    type: 'nanomaterials',
    cost: 18,
    description: '+6 shield, 10 damage enemy.',
    effect: orbitalCannon,
  },
  {
    id: 'nm_034',
    name: 'Core Reactor',
    type: 'nanomaterials',
    cost: 24,
    description: '+20 shield, +8 integrity.',
    effect: coreReactor,
  },
];
