import { ICard } from 'src/cards/types/cards.types';
import {
  unstableOre,
  seismicShock,
  asteroidCollapse,
  quantumCoin,
  terraCore,
  mineralGarden,
  orbitalInnovation,
  basicShield,
  overtimeShield,
  planetaryWall,
  foundationArray,
  orbitalMines,
  asteroidVein,
  mineCollapse,
  techHijack,
  reinforcedPlating,
  subterraneanStreams,
  orbitalDrill,
  cosmicExcavator,
  laborArray,
  shockwave,
  grandShield,
  hiddenCavity,
  orbitalVault,
  plasmaSpire,
  orbitalBarricade,
  stellarCore,
  orbitalBastion,
  fortifyArray,
  newFrontiers,
  ultimateShield,
  fieldSwap,
  orbitalCannon,
  coreReactor,
} from './nanomaterials.effects';

export const nanomaterialsCards: ICard[] = [
  {
    id: 'nm_001',
    name: 'Unstable Ore',
    type: 'nanomaterials',
    cost: 0,
    description: 'All players lose 8 nanomaterials.',
    effect: unstableOre,
  },
  {
    id: 'nm_002',
    name: 'Seismic Shock',
    type: 'nanomaterials',
    cost: 0,
    description: '-1 mine for all players.',
    effect: seismicShock,
  },
  {
    id: 'nm_003',
    name: 'Asteroid Collapse',
    type: 'nanomaterials',
    cost: 0,
    description: '-1 enemy mine, +10 planet integrity, +5 energy.',
    effect: asteroidCollapse,
  },
  {
    id: 'nm_004',
    name: 'Quantum Coin',
    type: 'nanomaterials',
    cost: 0,
    description: '+2 nanomaterials, +2 energy, play again.',
    effect: quantumCoin,
  },
  {
    id: 'nm_005',
    name: 'Terra Core',
    type: 'nanomaterials',
    cost: 1,
    description: '+1 planet integrity, play again.',
    effect: terraCore,
  },
  {
    id: 'nm_006',
    name: 'Mineral Garden',
    type: 'nanomaterials',
    cost: 1,
    description: '+1 planet integrity, +1 tower, +2 drones.',
    effect: mineralGarden,
  },
  {
    id: 'nm_007',
    name: 'Orbital Innovation',
    type: 'nanomaterials',
    cost: 2,
    description: '+1 mine all players, +4 energy.',
    effect: orbitalInnovation,
  },
  {
    id: 'nm_008',
    name: 'Basic Shield',
    type: 'nanomaterials',
    cost: 2,
    description: '+3 planet integrity.',
    effect: basicShield,
  },
  {
    id: 'nm_009',
    name: 'Overtime Shield',
    type: 'nanomaterials',
    cost: 2,
    description: '+5 planet integrity, lose 6 energy.',
    effect: overtimeShield,
  },
  {
    id: 'nm_010',
    name: 'Planetary Wall',
    type: 'nanomaterials',
    cost: 3,
    description: '+4 planet integrity.',
    effect: planetaryWall,
  },
  {
    id: 'nm_011',
    name: 'Foundation Array',
    type: 'nanomaterials',
    cost: 3,
    description: 'If planet integrity=0, +5 integrity, else +3 integrity.',
    effect: foundationArray,
  },
  {
    id: 'nm_012',
    name: 'Orbital Mines',
    type: 'nanomaterials',
    cost: 3,
    description: '+1 mine.',
    effect: orbitalMines,
  },
  {
    id: 'nm_013',
    name: 'Asteroid Vein',
    type: 'nanomaterials',
    cost: 4,
    description: '+2 mine if less than enemy, else +1.',
    effect: asteroidVein,
  },
  {
    id: 'nm_014',
    name: 'Mine Collapse',
    type: 'nanomaterials',
    cost: 4,
    description: '-1 enemy mine.',
    effect: mineCollapse,
  },
  {
    id: 'nm_015',
    name: 'Tech Hijack',
    type: 'nanomaterials',
    cost: 5,
    description: 'Set your mines equal to enemy if lower.',
    effect: techHijack,
  },
  {
    id: 'nm_016',
    name: 'Reinforced Plating',
    type: 'nanomaterials',
    cost: 5,
    description: '+6 planet integrity.',
    effect: reinforcedPlating,
  },
  {
    id: 'nm_017',
    name: 'Subterranean Streams',
    type: 'nanomaterials',
    cost: 6,
    description: 'If weaker, lose 1 barrack, +2 tower.',
    effect: subterraneanStreams,
  },
  {
    id: 'nm_018',
    name: 'Orbital Drill',
    type: 'nanomaterials',
    cost: 6,
    description: '+2 mines.',
    effect: orbitalDrill,
  },
  {
    id: 'nm_019',
    name: 'Cosmic Excavator',
    type: 'nanomaterials',
    cost: 7,
    description: '+4 integrity, +1 mine.',
    effect: cosmicExcavator,
  },
  {
    id: 'nm_020',
    name: 'Labor Array',
    type: 'nanomaterials',
    cost: 7,
    description: '+9 integrity, lose 5 drones.',
    effect: laborArray,
  },
  {
    id: 'nm_021',
    name: 'Shockwave',
    type: 'nanomaterials',
    cost: 7,
    description: 'All planets lose 5 integrity, play again.',
    effect: shockwave,
  },
  {
    id: 'nm_022',
    name: 'Grand Shield',
    type: 'nanomaterials',
    cost: 8,
    description: '+8 planet integrity.',
    effect: grandShield,
  },
  {
    id: 'nm_023',
    name: 'Hidden Cavity',
    type: 'nanomaterials',
    cost: 8,
    description: '+1 energy, play again.',
    effect: hiddenCavity,
  },
  {
    id: 'nm_024',
    name: 'Orbital Vault',
    type: 'nanomaterials',
    cost: 9,
    description: '+5 integrity, +1 barrack.',
    effect: orbitalVault,
  },
  {
    id: 'nm_025',
    name: 'Plasma Spire',
    type: 'nanomaterials',
    cost: 9,
    description: '+7 integrity, +7 energy.',
    effect: plasmaSpire,
  },
  {
    id: 'nm_026',
    name: 'Orbital Barricade',
    type: 'nanomaterials',
    cost: 10,
    description: '+6 drones, +6 integrity, +1 barrack if less than enemy.',
    effect: orbitalBarricade,
  },
  {
    id: 'nm_027',
    name: 'Stellar Core',
    type: 'nanomaterials',
    cost: 11,
    description: '+6 integrity, +3 tower.',
    effect: stellarCore,
  },
  {
    id: 'nm_028',
    name: 'Orbital Bastion',
    type: 'nanomaterials',
    cost: 13,
    description: '+12 integrity.',
    effect: orbitalBastion,
  },
  {
    id: 'nm_029',
    name: 'Fortify Array',
    type: 'nanomaterials',
    cost: 14,
    description: '+7 integrity, 6 damage to enemy.',
    effect: fortifyArray,
  },
  {
    id: 'nm_030',
    name: 'New Frontiers',
    type: 'nanomaterials',
    cost: 15,
    description: '+8 integrity, +5 tower.',
    effect: newFrontiers,
  },
  {
    id: 'nm_031',
    name: 'Ultimate Shield',
    type: 'nanomaterials',
    cost: 16,
    description: '+15 integrity.',
    effect: ultimateShield,
  },
  {
    id: 'nm_032',
    name: 'Field Swap',
    type: 'nanomaterials',
    cost: 17,
    description: 'Swap your and enemy integrity.',
    effect: fieldSwap,
  },
  {
    id: 'nm_033',
    name: 'Orbital Cannon',
    type: 'nanomaterials',
    cost: 18,
    description: '+6 integrity, 10 damage to enemy.',
    effect: orbitalCannon,
  },
  {
    id: 'nm_034',
    name: 'Core Reactor',
    type: 'nanomaterials',
    cost: 24,
    description: '+20 integrity, +8 energy.',
    effect: coreReactor,
  },
];
