import { ICard } from 'src/cards/types/cards.types';
import {
  rogueSignal,
  lunarPulse,
  microDrone,
  echoPulse,
  ionLance,
  swarmStrike,
  droneReinforce,
  orbitalStrike,
  berserkModule,
  sniperDrone,
  nebulaLauncher,
  demolisher,
  voidPulse,
  rampageDrone,
  microSerpents,
  titanCannon,
  phantomEmitter,
  tutorDrone,
  voidTurret,
  breakerBeam,
  singularityRay,
  wolfStrike,
  sharpshotDrone,
  corrosiveCloud,
  rockDriller,
  scavenger,
  assaultModule,
  piercingDrone,
  shockCrawler,
  darkVanguard,
  pegasusLancer,
  novaDragon,
} from './drones.effects';

export const dronesCards: ICard[] = [
  {
    id: 'dr_001',
    name: 'Rogue Signal',
    type: 'drones',
    cost: 0,
    description: 'All players lose 6 drones.',
    effect: rogueSignal,
  },
  {
    id: 'dr_002',
    name: 'Lunar Pulse',
    type: 'drones',
    cost: 0,
    description: 'All +1 drone/turn; you gain 3 drones.',
    effect: lunarPulse,
  },
  {
    id: 'dr_003',
    name: 'Micro Drone',
    type: 'drones',
    cost: 1,
    description: '4 damage enemy, lose 3 energy.',
    effect: microDrone,
  },
  {
    id: 'dr_004',
    name: 'Echo Pulse',
    type: 'drones',
    cost: 1,
    description: '2 damage enemy. Play again.',
    effect: echoPulse,
  },
  {
    id: 'dr_005',
    name: 'Ion Lance',
    type: 'drones',
    cost: 2,
    description: '3 damage enemy, +1 energy.',
    effect: ionLance,
  },
  {
    id: 'dr_006',
    name: 'Swarm Strike',
    type: 'drones',
    cost: 2,
    description: 'if shield > enemy, 3 damage, else 2 damage.',
    effect: swarmStrike,
  },
  {
    id: 'dr_007',
    name: 'Drone Reinforce',
    type: 'drones',
    cost: 3,
    description: '+1 drone/turn.',
    effect: droneReinforce,
  },
  {
    id: 'dr_008',
    name: 'Orbital Strike',
    type: 'drones',
    cost: 3,
    description: '6 damage enemy.',
    effect: orbitalStrike,
  },
  {
    id: 'dr_009',
    name: 'Berserk Module',
    type: 'drones',
    cost: 4,
    description: '8 damage enemy, 3 damage self.',
    effect: berserkModule,
  },
  {
    id: 'dr_010',
    name: 'Sniper Drone',
    type: 'drones',
    cost: 4,
    description: '3 damage enemy, 1 damage self.',
    effect: sniperDrone,
  },
  {
    id: 'dr_011',
    name: 'Nebula Launcher',
    type: 'drones',
    cost: 5,
    description: '4 damage enemy, +3 shield.',
    effect: nebulaLauncher,
  },
  {
    id: 'dr_012',
    name: 'Demolisher',
    type: 'drones',
    cost: 5,
    description: '6 damage enemy.',
    effect: demolisher,
  },
  {
    id: 'dr_013',
    name: 'Void Pulse',
    type: 'drones',
    cost: 5,
    description: '6 damage all, all lose 5 drones.',
    effect: voidPulse,
  },
  {
    id: 'dr_014',
    name: 'Rampage Drone',
    type: 'drones',
    cost: 6,
    description: '6 damage enemy, enemy loses 3 drones.',
    effect: rampageDrone,
  },
  {
    id: 'dr_015',
    name: 'Micro Serpents',
    type: 'drones',
    cost: 6,
    description: '4 damage enemy planet.',
    effect: microSerpents,
  },
  {
    id: 'dr_016',
    name: 'Titan Cannon',
    type: 'drones',
    cost: 6,
    description: '7 damage enemy.',
    effect: titanCannon,
  },
  {
    id: 'dr_017',
    name: 'Phantom Emitter',
    type: 'drones',
    cost: 6,
    description: '2 damage enemy. Play again.',
    effect: phantomEmitter,
  },
  {
    id: 'dr_018',
    name: 'Tutor Drone',
    type: 'drones',
    cost: 7,
    description: '+2 drones/turn.',
    effect: tutorDrone,
  },
  {
    id: 'dr_019',
    name: 'Void Turret',
    type: 'drones',
    cost: 8,
    description: '2 damage, +4 shield, +2 integrity.',
    effect: voidTurret,
  },
  {
    id: 'dr_020',
    name: 'Breaker Beam',
    type: 'drones',
    cost: 8,
    description: 'if enemy shield = 0, 10 damage, else 6 damage.',
    effect: breakerBeam,
  },
  {
    id: 'dr_021',
    name: 'Singularity Ray',
    type: 'drones',
    cost: 9,
    description: 'if drones < enemy, 12 damage, else 8 damage.',
    effect: singularityRay,
  },
  {
    id: 'dr_022',
    name: 'Wolf Strike',
    type: 'drones',
    cost: 9,
    description: '9 damage enemy.',
    effect: wolfStrike,
  },
  {
    id: 'dr_023',
    name: 'Sharpshot Drone',
    type: 'drones',
    cost: 10,
    description: 'if shield > enemy, 6 damage, else 6 damage.',
    effect: sharpshotDrone,
  },
  {
    id: 'dr_024',
    name: 'Corrosive Cloud',
    type: 'drones',
    cost: 11,
    description: 'if shield > 10, 10 damage, else 7 damage.',
    effect: corrosiveCloud,
  },
  {
    id: 'dr_025',
    name: 'Rock Driller',
    type: 'drones',
    cost: 11,
    description: '8 damage; -1 enemy nanomaterial/turn.',
    effect: rockDriller,
  },
  {
    id: 'dr_026',
    name: 'Scavenger',
    type: 'drones',
    cost: 12,
    description: 'Enemy lose 10 energy & 5 nanomaterials.',
    effect: scavenger,
  },
  {
    id: 'dr_027',
    name: 'Assault Module',
    type: 'drones',
    cost: 13,
    description: '13 damage enemy, lose 3 psi energy.',
    effect: assaultModule,
  },
  {
    id: 'dr_028',
    name: 'Piercing Drone',
    type: 'drones',
    cost: 14,
    description: '5 damage planet, enemy loses 6 drones.',
    effect: piercingDrone,
  },
  {
    id: 'dr_029',
    name: 'Shock Crawler',
    type: 'drones',
    cost: 15,
    description: '10 damage, +4 shield.',
    effect: shockCrawler,
  },
  {
    id: 'dr_030',
    name: 'Dark Vanguard',
    type: 'drones',
    cost: 17,
    description: '10 damage; enemy drones -1/turn.',
    effect: darkVanguard,
  },
  {
    id: 'dr_031',
    name: 'Pegasus Lancer',
    type: 'drones',
    cost: 18,
    description: '12 damage enemy planet.',
    effect: pegasusLancer,
  },
  {
    id: 'dr_032',
    name: 'Nova Dragon',
    type: 'drones',
    cost: 25,
    description: '20 damage enemy, -1 drone/turn, -10 psi energy.',
    effect: novaDragon,
  },
];
