import { ICard } from 'src/cards/types/cards.types';
import {
  quantumShard,
  nebulaCascade,
  prismCore,
  amethystSpire,
  smokyQuartz,
  cosmicRift,
  forceBurst,
  rubyNova,
  psiWeaver,
  eclipseRay,
  stellarSpear,
  cosmicAid,
  initiationSequence,
  cosmicDiscord,
  oreVein,
  matrixPulse,
  emeraldBeam,
  harmonyArray,
  softStone,
  parityCore,
  fragmentationPulse,
  solidification,
  pearlWisdom,
  sapphireBeacon,
  lightningSurge,
  crystalShield,
  rubyFlare,
  empathyCore,
  orbitalReactor,
  diamondCore,
  luminousStone,
  meditationCore,
  dragonEye,
} from './psiEnergy.effects';

export const psiEnergyCards: ICard[] = [
  {
    id: 'pe_001',
    name: 'Quantum Shard',
    type: 'psiEnergy',
    cost: 0,
    description: '+2 integrity if lower than enemy, else +1.',
    effect: quantumShard,
  },
  {
    id: 'pe_002',
    name: 'Nebula Cascade',
    type: 'psiEnergy',
    cost: 0,
    description: 'All players +1 integrity, +3 energy.',
    effect: nebulaCascade,
  },
  {
    id: 'pe_003',
    name: 'Prism Core',
    type: 'psiEnergy',
    cost: 1,
    description: '+1 integrity. Play again.',
    effect: prismCore,
  },
  {
    id: 'pe_004',
    name: 'Amethyst Spire',
    type: 'psiEnergy',
    cost: 2,
    description: '+3 planet integrity.',
    effect: amethystSpire,
  },
  {
    id: 'pe_005',
    name: 'Smoky Quartz',
    type: 'psiEnergy',
    cost: 2,
    description: '1 damage to planet integrity. Play again.',
    effect: smokyQuartz,
  },
  {
    id: 'pe_006',
    name: 'Cosmic Rift',
    type: 'psiEnergy',
    cost: 2,
    description: '3 damage to planet integrity.',
    effect: cosmicRift,
  },
  {
    id: 'pe_007',
    name: 'Force Burst',
    type: 'psiEnergy',
    cost: 3,
    description: '-5 integrity self, +2 psi energy per turn.',
    effect: forceBurst,
  },
  {
    id: 'pe_008',
    name: 'Ruby Nova',
    type: 'psiEnergy',
    cost: 3,
    description: '+5 planet integrity.',
    effect: rubyNova,
  },
  {
    id: 'pe_009',
    name: 'Psi Weaver',
    type: 'psiEnergy',
    cost: 3,
    description: '+1 psi energy.',
    effect: psiWeaver,
  },
  {
    id: 'pe_010',
    name: 'Eclipse Ray',
    type: 'psiEnergy',
    cost: 4,
    description: '+2 integrity self, 2 damage enemy.',
    effect: eclipseRay,
  },
  {
    id: 'pe_011',
    name: 'Stellar Spear',
    type: 'psiEnergy',
    cost: 4,
    description: '5 damage to enemy planet.',
    effect: stellarSpear,
  },
  {
    id: 'pe_012',
    name: 'Cosmic Aid',
    type: 'psiEnergy',
    cost: 4,
    description: '+7 integrity, lose 10 nanomaterials.',
    effect: cosmicAid,
  },
  {
    id: 'pe_013',
    name: 'Initiation Sequence',
    type: 'psiEnergy',
    cost: 5,
    description: '+4 integrity, -3 drones, 2 damage integrity.',
    effect: initiationSequence,
  },
  {
    id: 'pe_014',
    name: 'Cosmic Discord',
    type: 'psiEnergy',
    cost: 5,
    description: '7 damage all planets, -1 drone/turn all.',
    effect: cosmicDiscord,
  },
  {
    id: 'pe_015',
    name: 'Ore Vein',
    type: 'psiEnergy',
    cost: 5,
    description: '+8 planet integrity.',
    effect: oreVein,
  },
  {
    id: 'pe_016',
    name: 'Matrix Pulse',
    type: 'psiEnergy',
    cost: 6,
    description: '+3 integrity, enemy +1, +1 psi/turn.',
    effect: matrixPulse,
  },
  {
    id: 'pe_017',
    name: 'Emerald Beam',
    type: 'psiEnergy',
    cost: 6,
    description: '+8 planet integrity.',
    effect: emeraldBeam,
  },
  {
    id: 'pe_018',
    name: 'Harmony Array',
    type: 'psiEnergy',
    cost: 7,
    description: '+3 integrity, +3 shield, +1 psi/turn.',
    effect: harmonyArray,
  },
  {
    id: 'pe_019',
    name: 'Soft Stone',
    type: 'psiEnergy',
    cost: 7,
    description: '+5 integrity, enemy -6 nanomaterials.',
    effect: softStone,
  },
  {
    id: 'pe_020',
    name: 'Parity Core',
    type: 'psiEnergy',
    cost: 7,
    description: 'Set +1 psi/turn. to strongest player.',
    effect: parityCore,
  },
  {
    id: 'pe_021',
    name: 'Fragmentation Pulse',
    type: 'psiEnergy',
    cost: 8,
    description: '-1 psi/turn, 9 damage enemy planet.',
    effect: fragmentationPulse,
  },
  {
    id: 'pe_022',
    name: 'Solidification',
    type: 'psiEnergy',
    cost: 8,
    description: '+11 integrity, -6 shield.',
    effect: solidification,
  },
  {
    id: 'pe_023',
    name: 'Pearl Wisdom',
    type: 'psiEnergy',
    cost: 9,
    description: '+5 integrity, +1 psi energy per turn.',
    effect: pearlWisdom,
  },
  {
    id: 'pe_024',
    name: 'Sapphire Beacon',
    type: 'psiEnergy',
    cost: 10,
    description: '+11 planet integrity.',
    effect: sapphireBeacon,
  },
  {
    id: 'pe_025',
    name: 'Lightning Surge',
    type: 'psiEnergy',
    cost: 11,
    description: 'If higher: 8 dmg enemy integrity; else 8 dmg all.',
    effect: lightningSurge,
  },
  {
    id: 'pe_026',
    name: 'Crystal Shield',
    type: 'psiEnergy',
    cost: 12,
    description: '+8 integrity, +3 shield.',
    effect: crystalShield,
  },
  {
    id: 'pe_027',
    name: 'Ruby Flare',
    type: 'psiEnergy',
    cost: 13,
    description: '+6 integrity, 4 damage enemy planet.',
    effect: rubyFlare,
  },
  {
    id: 'pe_028',
    name: 'Empathy Core',
    type: 'psiEnergy',
    cost: 14,
    description: '+8 integrity, +1 drone per turn.',
    effect: empathyCore,
  },
  {
    id: 'pe_029',
    name: 'Orbital Reactor',
    type: 'psiEnergy',
    cost: 15,
    description: '+10 integrity, +5 shield, +5 drones.',
    effect: orbitalReactor,
  },
  {
    id: 'pe_030',
    name: 'Diamond Core',
    type: 'psiEnergy',
    cost: 16,
    description: '+15 planet integrity.',
    effect: diamondCore,
  },
  {
    id: 'pe_031',
    name: 'Luminous Stone',
    type: 'psiEnergy',
    cost: 17,
    description: '+12 integrity, 6 damage enemy.',
    effect: luminousStone,
  },
  {
    id: 'pe_032',
    name: 'Meditation Core',
    type: 'psiEnergy',
    cost: 18,
    description: '+13 integrity, +6 drones, +6 nanomaterials.',
    effect: meditationCore,
  },
  {
    id: 'pe_033',
    name: 'Dragon Eye',
    type: 'psiEnergy',
    cost: 21,
    description: '+20 integrity.',
    effect: dragonEye,
  },
];
