import {
  terraformOrbit,
  droneSwarmAssault,
  planetaryPsiReactor,
  nanomaterialBoost,
  shieldModulation,
  psiBlast,
  droneReinforcement,
  planetCloaking,
  droneCriticalStrike,
  shieldRepairArray,
} from './cards.effects';
import { ICard } from './types/cards.types';

export const cards: ICard[] = [
  {
    id: 'card_001',
    name: 'Terraform Orbit',
    type: 'nanomaterials',
    cost: 5,
    description: 'Increases planet integrity by 10.',
    effect: terraformOrbit,
  },
  {
    id: 'card_002',
    name: 'Drone Swarm Assault',
    type: 'drones',
    cost: 4,
    description:
      'Deals 8 damage to the opponent: first to shields, then to planet integrity.',
    effect: droneSwarmAssault,
  },
  {
    id: 'card_003',
    name: 'Planetary Psi Reactor',
    type: 'psiEnergy',
    cost: 3,
    description: 'Adds 1 PsiEnergy production.',
    effect: planetaryPsiReactor,
  },
  {
    id: 'card_004',
    name: 'Nanomaterial Boost',
    type: 'nanomaterials',
    cost: 2,
    description: 'Increases nanomaterial production by 2.',
    effect: nanomaterialBoost,
  },
  {
    id: 'card_005',
    name: 'Shield Modulation',
    type: 'psiEnergy',
    cost: 1,
    description: 'Increases your planet shield by 8.',
    effect: shieldModulation,
  },
  {
    id: 'card_006',
    name: 'Psi Blast',
    type: 'psiEnergy',
    cost: 4,
    description: 'Reduces the opponent’s shield by 10.',
    effect: psiBlast,
  },
  {
    id: 'card_007',
    name: 'Drone Reinforcement',
    type: 'drones',
    cost: 3,
    description: 'Deals 6 damage to the opponent and heals 5 planet integrity.',
    effect: droneReinforcement,
  },
  {
    id: 'card_008',
    name: 'Planet Cloaking',
    type: 'nanomaterials',
    cost: 3,
    description: 'Increases shield by 5 and planet integrity by 3.',
    effect: planetCloaking,
  },
  {
    id: 'card_009',
    name: 'Drone Critical Strike',
    type: 'drones',
    cost: 5,
    description: 'Deals 15 damage to opponent’s planet.',
    effect: droneCriticalStrike,
  },
  {
    id: 'card_010',
    name: 'Shield Repair Array',
    type: 'nanomaterials',
    cost: 4,
    description: 'Increases your planet shield by 12.',
    effect: shieldRepairArray,
  },
];
